replicaCount: 2
image:
  repository: <YOUR_DOCKER_REGISTRY>/my-app
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  host: my-app.local
  annotations: {}
